# Site settings
title: Nauji Algoritmai
email: info@naujialgoritmai.lt
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.naujialgoritmai.lt" # the base hostname & protocol for your site

# User setting
owner: Nauji Algoritmai
email: info@naujialgoritmai.lt
facebook_username: example
twitter_username: example
github_username: naujialgoritmai
address:
  - line: MB „Nauji Algoritmai“
  - line: K. Baršausko 59, Kaunas
  - line: Įmonės kodas: 121289694
  - line: Ne PVM mokėtojas
  - line: Duomenys kaupiami Juridinių asmenų registre, tvarkomame VĮ 'Registrų centras'
  # Feel free to add more lines here 
copyright: NA

# API settings
google_api_key: AIzaSyA8H0jVz_6Hc273rqNYKQ6AAiBvQfVKmYQ

# Build settings
markdown: kramdown